### ISSUE TITLE
Error with png_gth_to_nii.ipynb on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Liurchen** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#3]
I am running the project follow README.md, in the data pre-processing procedure, which converting downloaded data (T2 fold) to nii files in 3D for the ease of reading. An error occurred, when I run ./data/CHAOST2/png_gth_to_nii.ipynp to convert ground truth with png format to nifti. Below is the specific information the terminal shows:

```python
[NbConvertApp] Converting notebook png_gth_to_nii.ipynb to notebook
[NbConvertApp] Executing notebook with the kernel: python3

Traceback (most recent call last):
  File "/home/rcliu/.local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/rcliu/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/rcliu/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nest_asyncio.py", line 95, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/rcliu/.local/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:

------------------
#### Write them to nii files for the ease of loading in future
for curr_id in ids:
    pngs = glob.glob(f'./MR/{curr_id}/T2SPIR/Ground/*.png')
    pngs = sorted(pngs, key = lambda x: int(os.path.basename(x).split("-")[-1].split(".png")[0]))
    buffer = []

    for fid in pngs:
        buffer.append(PIL.Image.open(fid))

    vol = np.stack(buffer, axis = 0)
    # flip correction
    vol = np.flip(vol, axis = 1).copy()
    # remap values
    for new_val, old_val in enumerate(sorted(np.unique(vol))):
        vol[vol == old_val] = new_val

    # get reference
    ref_img = f'./niis/T2SPIR/image_{curr_id}.nii.gz'
    img_o = sitk.ReadImage(ref_img)
    vol_o = nio.np2itk(img=vol, ref_obj=img_o)
    sitk.WriteImage(vol_o, f'{OUT_DIR}/label_{curr_id}.nii.gz')
    print(f'image with id {curr_id} has been saved!')


------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-70a020772866> in <module>
     18     ref_img = f'./niis/T2SPIR/image_{curr_id}.nii.gz'
     19     img_o = sitk.ReadImage(ref_img)
---> 20     vol_o = nio.np2itk(img=vol, ref_obj=img_o)
     21     sitk.WriteImage(vol_o, f'{OUT_DIR}/label_{curr_id}.nii.gz')
     22     print(f'image with id {curr_id} has been saved!')

AttributeError: module 'niftiio' has no attribute 'np2itk'
AttributeError: module 'niftiio' has no attribute 'np2itk'
```

Then I look into niftiio.py located in ./dataloaders/, there is no np2itk method:

```python
"""
Utils for datasets
"""
import numpy as np

import numpy as np
import SimpleITK as sitk


def read_nii_bysitk(input_fid, peel_info = False):
    """ read nii to numpy through simpleitk
        peelinfo: taking direction, origin, spacing and metadata out
    """
    img_obj = sitk.ReadImage(input_fid)
    img_np = sitk.GetArrayFromImage(img_obj)
    if peel_info:
        info_obj = {
                "spacing": img_obj.GetSpacing(),
                "origin": img_obj.GetOrigin(),
                "direction": img_obj.GetDirection(),
                "array_size": img_np.shape
                }
        return img_np, info_obj
    else:
        return img_np

def convert_to_sitk(input_mat, peeled_info):
    """
    write a numpy array to sitk image object with essential meta-data
    """
    nii_obj = sitk.GetImageFromArray(input_mat)
    if peeled_info:
        nii_obj.SetSpacing(  peeled_info["spacing"] )
        nii_obj.SetOrigin(   peeled_info["origin"] )
        nii_obj.SetDirection(peeled_info["direction"] )
    return nii_obj

```

So I wonder is there some code missing in the file niftiio.py?  And how to get this project running well?

**Comment by cheng-01037** [comment]
Thanks for pointing this out. Will fix these dependency issues soon.

Best,
Cheng

**Comment by Liurchen** [comment]
Sure, it works, thanks for fixing this.
