### ISSUE TITLE
I want to run a single category dataset. How can I set it to a single category

### ISSUE THREAD

**Issue by enoch1025** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#39]
I want to run a single category dataset. How can I set it to a single category
please tell me, thank eyeryone!!!!!!!!

**Comment by enoch1025** [comment]
./examples/train_ssl_abdominal_ct.sh 
===================================
train_SABS_Superpix_lbgroup0_scale_MIDDLE_vfold0
WARNING - root - Changed type of config entry "min_fg_data" from str to int
INFO - mySSL - Running command 'main'
INFO - mySSL - Started run with ID "12"
INFO - main - ###### Create model ######
###### NETWORK: Using ms-coco initialization ######
INFO - main - ###### Load data ######
INFO - main - ###### Labels excluded in training : [2, 3] ######
INFO - main - ###### Unseen labels evaluated in testing: [2, 3] ######
###### Dataset: the following classes has been excluded [2, 3]######
###### DEBUG_DATASET CT_STATS NORMALIZED MEAN 0.2503295103060257 STD 0.22380904778564215 ######
###### Initial scans loaded: ######
['7', '8', '9', '10', '11', '12']
INFO - main - ###### Set optimizer ######
INFO - main - ###### Training ######
INFO - main - ###### This is epoch 0 of 100 epoches ######
/home/wangyixiong/anaconda3/envs/self/lib/python3.7/site-packages/torch/nn/functional.py:2973: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
Faulty batch detected, skip
^CWARNING - mySSL - Aborted after 0:00:20!
Traceback (most recent call last):
  File "training.py", line 30, in <module>
    @ex.automain
  File "/home/wangyixiong/anaconda3/envs/self/lib/python3.7/site-packages/sacred/experiment.py", line 140, in automain
    self.run_commandline()
  File "/home/wangyixiong/anaconda3/envs/self/lib/python3.7/site-packages/sacred/experiment.py", line 263, in run_commandline
    return self.run(cmd_name, config_updates, nam

**Comment by ibasaisaac** [comment]
I am also getting  "Faulty batch detected, skip". How to fix this?
